name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 (API)
        run: flake8 api

      - name: Run flake8 (Worker)
        run: flake8 worker
         # ---------------- FRONTEND LINT ----------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint

      # ---------------- DOCKER LINT ----------------
      - name: Lint Dockerfiles (Hadolint)
        run: |
          docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < api/Dockerfile
          docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < worker/Dockerfile
          docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < frontend/Dockerfile
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r api/requirements.txt pytest httpx

      - name: Run API tests
        env:
          PYTHONPATH: .
        run: pytest api/tests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start local Docker registry
        run: docker run -d -p 5000:5000 --name registry registry:2

      # API
      - name: Build and push API
        run: |
          docker build -t api:latest ./api
          docker tag api:latest localhost:5000/api:${{ github.sha }}
          docker tag api:latest localhost:5000/api:latest
          docker push localhost:5000/api:${{ github.sha }}
          docker push localhost:5000/api:latest

      # Worker
      - name: Build and push Worker
        run: |
          docker build -t worker:latest ./worker
          docker tag worker:latest localhost:5000/worker:${{ github.sha }}
          docker tag worker:latest localhost:5000/worker:latest
          docker push localhost:5000/worker:${{ github.sha }}
          docker push localhost:5000/worker:latest

      # Frontend
      - name: Build and push Frontend
        run: |
          docker build -t frontend:latest ./frontend
          docker tag frontend:latest localhost:5000/frontend:${{ github.sha }}
          docker tag frontend:latest localhost:5000/frontend:latest
          docker push localhost:5000/frontend:${{ github.sha }}
          docker push localhost:5000/frontend:latest

  security_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

      - name: Scan API image
        run: |
          trivy image --severity CRITICAL --exit-code 1 \
          --format sarif -o trivy-api.sarif \
          localhost:5000/api:latest

      - name: Scan Worker image
        run: |
          trivy image --severity CRITICAL --exit-code 1 \
          --format sarif -o trivy-worker.sarif \
          localhost:5000/worker:latest

      - name: Scan Frontend image
        run: |
          trivy image --severity CRITICAL --exit-code 1 \
          --format sarif -o trivy-frontend.sarif \
          localhost:5000/frontend:latest

      - name: Upload SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-api.sarif
            trivy-worker.sarif
            trivy-frontend.sarif 